"""added user_id to transactions

Revision ID: d41f74d1b8ab
Revises: 0002
Create Date: 2026-09-25 12:16:06.420854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41f74d1b8ab'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Применяет изменения схемы.
def upgrade() -> None:
    """Upgrade schema."""
    connection = op.get_bind()
    has_transactions = connection.execute(sa.text('SELECT 1 FROM transactions LIMIT 1')).first()
    if has_transactions and not connection.execute(sa.text('SELECT 1 FROM users WHERE id = 1')).first():
        raise RuntimeError('Для переноса существующих транзакций нужен пользователь id = 1')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_user_id_users', 'users', ['user_id'], ['id'])

    # Назначает владельца старым записям перед запретом пустого значения.
    connection.execute(sa.text('UPDATE transactions SET user_id = 1 WHERE user_id IS NULL'))
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)


# Отменяет изменения схемы.
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
